sudo = required

services:
  - docker

cache:
  directories:
    - /home/travis/docker

  env:
    - UBUNTU_RELEASE=trusty \
        DOCKER_CACHE_FILE=/home/travis/docker/trusty-cache.tar.gz
    - UBUNTU_RELEASE=xenial \
        DOCKER_CACHE_FILE=/home/travis/docker/xenial-cache.tar.gz
      `
before_install:
  - scripts/load_docker_cache.sh

install: true

scripts:
  - docker build ${TRAVIS_BUILD_DIR} \
      -t attiny85sim:${UBUNTU_RELEASE} -f Dockerfile.${UBUNTU_RELEASE}
  - scripts/save_docker_cache.sh

